os:
    - linux
    - os x

language: python
python:
    - 2.7
    - 2.6
    - 3.3
    - 3.4
    - 3.5

install:
    - python setup.py install

script:
    - nhentai --search umaru
    - nhentai --ids=152503,146134 -t 10 --download --path=/tmp/
