os:
    - linux

language: python
python:
    - 2.7
    - 2.6
    - 3.3
    - 3.4
    - 3.5

install:
    - python setup.py install

script:
    - NHENTAI=https://nhentai.net nhentai --search umaru
    - NHENTAI=https://nhentai.net nhentai --id=152503,146134 -t 10 --path=/tmp/
